version: '2.1'


services:
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: QA_myapp
      MYSQL_USER: test_qa
      MYSQL_PASSWORD: qa_test

    image: "mysql:5.7"
    
    volumes:
      - /home/atom/atom/2021-2-QA-AUTO-PYTHON-VKGROUP-M-Gladyshev/Final-Project/config/db_docker:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD", "mysqladmin","-uroot","-ppass","ping","-h","127.0.0.1"]
      timeout: 1s
      retries: 30

  VK_mock:
    image: "vk_mock"

    environment:
      - HOST=0.0.0.0
      - PORT=8080

  QA_myapp:
    image:  "myapp:latest"

    volumes:
      - /home/atom/atom/2021-2-QA-AUTO-PYTHON-VKGROUP-M-Gladyshev/Final-Project/config/app_docker:/tmp/conf
    entrypoint: /app/myapp --config=/tmp/conf/config

    ports:
      - "8081:8080"
    
    depends_on:
      mysql:
        condition: service_healthy

  selenoid:
    image: "aerokube/selenoid"

    volumes:
      - /home/atom/atom/2021-2-QA-AUTO-PYTHON-VKGROUP-M-Gladyshev/Final-Project/config/selenoid_docker:/etc/selenoid
      - /var/run/docker.sock:/var/run/docker/sock
    
    command: ["-conf", "/etc/selenoid/browser.json"]

  tests:
    image: tests_do
    tty: true
    environment:
      - MARK=SQL
      - N=0

    volumes:
      - /home/atom/atom/2021-2-QA-AUTO-PYTHON-VKGROUP-M-Gladyshev/Final-Project/testing:/tmp/testing
      - $WORKSPACE/allure:/tmp/allure
    entrypoint: /bin/bash /tmp/testing/start_tests.sh
    depends_on:
      QA_myapp:
        condition: service_started
