- job:
    name: test-qa-pipeline
    description: "JJB Project, Pipeline\n"
    project-type: pipeline

    pipeline-scm:
      scm:
        - QA-scm
      script-path: "pipeline.groovy"

    wrappers:
      - timestamps
      - workspace-cleanup

    triggers:
      - pollscm:
          cron: '* * * * *'

    parameters:
      string(
             defaultValue: "api or ui",
             description: 'Pytest marks tests parameter',
             name: 'MARK'
        ) 
        string(
             defaultValue: "4",
             description: 'Workers number',
             name: 'WORKERS'
        ) 
    }